title: Deis Robotics
author: Robotics Club & co.
description: "Brandeis University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
sidebar: true        # show a sidebar instead of the usual header
show_description: true     #show the site description in the side bar
show_title: false        #always keep the site name visible

#styling
minimal: false             # keep simple style

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "masonoprice.github.io", title: "Deis Robotics", icon: dice-d12}
  - {file: "index.md", title: "Home",  icon: home }
  - {file: "guides.md", title: "Guides", icon: archive}
  - {file: "our_bots.md", title: "Projects", icon: clipboard}
  - {file: "calculations.md", title: "Calculations", icon: calculator}
  - {file: "about.md",  title: "About", icon: address-card}
  - {title: "Wiki", url: "https://wiki.nhrl.io/wiki/index.php/Krikit", icon: wikipedia-w}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/masonoprice/masonoprice.github.io"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
